spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/chatting
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console